---
- name: MySQL Failover Automation
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Stop MySQL Service
      service:
        name: mysql
        state: stopped
      when: inventory_hostname == "192.168.56.123"

    - name: Change MySQL Config for Master
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^server-id.*'
        line: 'server-id = 4'
      when: inventory_hostname == "192.168.56.123"

    - name: Change MySQL Config for Slave Primary
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^server-id.*'
        line: 'server-id = 5'
      when: inventory_hostname == "192.168.56.124"

    - name: Change MySQL Config for Slave Secondary
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^server-id.*'
        line: 'server-id = 6'
      when: inventory_hostname == "192.168.56.125"

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
      when: inventory_hostname == "192.168.56.123"

    - name: Stop Replica IO Thread
      command: "mysql -e 'STOP SLAVE IO_THREAD;'"
      when: inventory_hostname in ["192.168.56.124", "192.168.56.125"]

    - name: Remove Replication Settings on Slave Servers
      command: "mysql -e 'RESET SLAVE ALL;'"
      when: inventory_hostname in ["192.168.56.124", "192.168.56.125"]

    - name: Reset Slave on New Master
      command: "mysql -e 'CHANGE MASTER TO MASTER_HOST=\"192.168.56.123\", MASTER_USER=\"replica\", MASTER_PASSWORD=\"Dio140998:)\";'"
      when: inventory_hostname in ["192.168.56.124", "192.168.56.125"]

    - name: Start Replica IO Thread
      command: "mysql -e 'START SLAVE IO_THREAD;'"
      when: inventory_hostname in ["192.168.56.124", "192.168.56.125"]
